CREATE DATABASE db_marketplace

USE db_marketplace

CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name VARCHAR(50) NOT NULL,
	CPF BIGINT NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	Address VARCHAR(100) NULL,
)

CREATE TABLE Categories(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Description VARCHAR(50)
)

CREATE TABLE Products(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(150) NOT NULL,
	Price FLOAT NULL,
	FK_Creator INT NOT NULL,
	FK_Category INT NOT NULL,
	FOREIGN KEY (FK_Creator) REFERENCES Users (Id),
	FOREIGN KEY (FK_Category) REFERENCES Categories (Id)
)

CREATE TABLE Purchases(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	FK_Buyer INT NOT NULL,
	FK_Product INT NOT NULL,
	FOREIGN KEY (FK_Buyer) REFERENCES Users (Id),
	FOREIGN KEY (FK_Product) REFERENCES Products (Id)
)

DROP TABLE Users
DROP TABLE Categories
DROP TABLE Products
DROP TABLE Purchases