CREATE DATABASE db_ecommerce

USE db_ecommerce

CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Cellphone VARCHAR(15) NOT NULL,
	Password VARCHAR(25) NOT NULL,
	PaymentMethod VARCHAR(50) NULL,
	Adress VARCHAR(50) NULL
)

CREATE TABLE OrderedProducts(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Type VARCHAR(50) NOT NULL,
	Description VARCHAR(50) NOT NULL,
	Price FLOAT NOT NULL,
	Quantity INT NOT NULL,
	FK_User INT NOT NULL,
	FOREIGN KEY (FK_User) REFERENCES Users (Id)
)

CREATE TABLE Cart(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	FinalPrice FLOAT NOT NULL,
	ShippingCost FLOAT NOT NULL,
	Voucher VARCHAR(50) NULL,
	FK_User INT NOT NULL,
	FK_OrderedProduct INT NOT NULL,
)

CREATE TABLE PaymentMethod(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Type VARCHAR(50) NOT NULL,
	Installments VARCHAR(50) NOT NULL,
	FK_User INT NOT NULL
)