CREATE DATABASE db_socialmedianetwork

USE db_socialmedianetwork

CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Nickname VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Password VARCHAR(100) NOT NULL
)

CREATE TABLE Posts(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Themes VARCHAR(50) NOT NULL,
	Title VARCHAR(50) NOT NULL,
	Description VARCHAR(500) NOT NULL,
	Picture VARCHAR(50) NULL,
	FK_User INT NOT NULL,
	FOREIGN KEY (FK_User) REFERENCES Users (Id),
)

CREATE TABLE Groups(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Posts VARCHAR(8000) NULL,
	Picture VARCHAR(50) NULL,
	FK_User INT NOT NULL,
	FOREIGN KEY (FK_User) REFERENCES Users (Id)
)