CREATE DATABASE db_classifieds

USE db_classifieds

CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Cellphone VARCHAR(14) NOT NULL
)

CREATE TABLE Service(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Type VARCHAR(50) NOT NULL,
	Description VARCHAR(200) NOT NULL,
	Price FLOAT NOT NULL,
	Contact VARCHAR(50) NOT NULL,
	FK_User INT NOT NULL,
	FOREIGN KEY (FK_User) REFERENCES Users (Id)
)